### ISSUE TITLE
Computational Neuroscience W1D1 Tutorial 1

### ISSUE THREAD

**Issue by majauhar** [NeuromatchAcademy/course-content#1042]
There seems to be an issue with the interactive demo 4 on ISI functions explorer. If I play with the values, new plots are created after each modification, quickly creating tens of plots and it is then very difficult to keep track of and analyse. Would be great if there is only one plot and it is replotted on every modification. 

Link to the tutorial: https://colab.research.google.com/github/NeuromatchAcademy/course-content/blob/main/tutorials/W1D1_ModelTypes/student/W1D1_Tutorial1.ipynb#scrollTo=GPjtLkQaQX-P

Screenshots for reference:
![Screenshot 2023-07-10 at 12 56 25 PM](https://github.com/NeuromatchAcademy/course-content/assets/43479350/0945386d-4f6b-46d1-9ee4-601a6b729d7c)

![Screenshot 2023-07-10 at 12 56 37 PM](https://github.com/NeuromatchAcademy/course-content/assets/43479350/5fb2ac01-4f01-4a35-944a-f856872ff1f9)
![Screenshot 2023-07-10 at 12 56 41 PM](https://github.com/NeuromatchAcademy/course-content/assets/43479350/464f1c46-0576-495c-ba01-5996579daf7a)

**Comment by spirosChv** [comment]
@majauhar thanks for reporting this. We will upload a fix. Most probably something changed in the colab defaults.

One quick tweak for now is to add `plt.show()` at the end of the hidden code inside the `fit_plot` def.

**Comment by spirosChv** [comment]
@majauhar I have merged an upgrade, so now is working as expected.

**Comment by majauhar** [comment]
@spirosChv That's great. Thank you for quickly fixing it.
