### ISSUE TITLE
Issue on page /tutorials/W2D2_LinearSystems/student/W2D2_Tutorial2.html

### ISSUE THREAD

**Issue by kumarneelabh13** [NeuromatchAcademy/course-content#1063]
I think that in W2D2 (Linear Systems) Tutorial 2 (Markov Processes), in the Coding Exercise 2 figure, the labels should be "closed" and "open".

Currently they read, "closed to open" and "open to closed". But they're meant to indicate how the probability of being in state open/closed evolves with time.

**Comment by GaganaB** [comment]
Thanks @kumarneelabh13 for raising this issue. This has been worked on (Referenced: PR #1080)
Kind Regards.
