### ISSUE TITLE
Retina style interferes with student version creation

### ISSUE THREAD

**Issue by patrickmineault** [NeuromatchAcademy/course-content#110]
Some notebooks have retina plot styles (double the resolution), i.e.

`%config InlineBackend.figure_format = 'retina'`

For images to display correctly the size has to be written in the img tag (half the true size):

![image](https://user-images.githubusercontent.com/3516539/85486409-92286a00-b598-11ea-965a-a37b7d2e8094.png)

Fix this to prevent giant images, e.g. https://colab.research.google.com/github/NeuromatchAcademy/course-content/blob/master/tutorials/W1D3-ModelFitting/student/W1D3_Tutorial7.ipynb#scrollTo=W25y2KDnYRgN

**Comment by msarvestani** [comment]
I was wondering about that. Should I fix now for W1D3?

**Comment by mwaskom** [comment]
I think we generally want to keep retina inline images and that this should be solved in static image creation? I guess the steps are:

- detect retina mode
- use PIL to downsize static images?
