### ISSUE TITLE
Issue on page /tutorials/Schedule/shared_calendars.html

### ISSUE THREAD

**Issue by issa-garcia** [NeuromatchAcademy/course-content#1100]
Zone 5 hyperlink directs to "Academy Slot 2: Middle East / India" calender.

**Comment by issa-garcia** [comment]
@courtneydean33 I cannot find a version of Slot 5 calendar. If it helps the Computational Tools for Climate Science is very similar and just needs to be pushed a week backwards and have some other specific events added, e.g. professional events. https://calendar.google.com/calendar/u/0/embed?src=c_7e197485198b40038110d8ab59f79592a3fd46bb9e5357b0140865d83a062268@group.calendar.google.com&ctz=UTC

Please let me know if you would like me to help with this.

**Comment by courtneydean33** [comment]
Hi @issa-garcia -- i just double checked this and all the links are working for me. Can you check to see if the issues been fixed?

**Comment by issa-garcia** [comment]
Yes, it is fixed already. Thank you for fixing it and the response.
