### ISSUE TITLE
Week 1, Day 3, Tutorial 1, Equation incorrect

### ISSUE THREAD

**Issue by jhkirchner** [NeuromatchAcademy/course-content#111]
The equation for the optimal theta_hat

\begin{align}
\hat\theta = \sum_{i=1}^N \frac{x_i y_i}{x_i^2}
\end{align}

seems to be incorrect? Shouldn't it be:

\begin{align}
\hat\theta =  \frac{\sum_{i=1}^N x_i y_i}{\sum_{i=1}^N x_i^2}
\end{align}

Best,

Jan

**Comment by yhz-1995** [comment]
Same problem in "Finding the Maximum Likelihood Estimator" section of Week 1, Day 3, Tutorial 2.

**Comment by pehf** [comment]
thank you for catching this bad typo

**Comment by kdoelling1919** [comment]
I still see this typo in the instructor notebook of W1D3- Tutorial 1.
<img width="897" alt="image" src="https://user-images.githubusercontent.com/13767931/86349887-1e562380-bc62-11ea-9c9e-01774dd66ed4.png">
