### ISSUE TITLE
function restrict_spike_times in W1D1_Tutorial

### ISSUE THREAD

**Issue by iezqrom** [NeuromatchAcademy/course-content#112]
The argument interval in the function **restrict_spike_times** in [W1D1_Tutorial](https://github.com/NeuromatchAcademy/course-content/blob/master/tutorials/W1D1-ModelTypes/W1D1_Tutorial1.ipynb) doesn't appear inside. In the function, t_interval should be removed and the argument interval modified to t_interval

hope that helps!

**Comment by msarvestani** [comment]
This has been resolved.  I'll close .
