### ISSUE TITLE
W1D1-Tutorial2

### ISSUE THREAD

**Issue by KulikovaSofya** [NeuromatchAcademy/course-content#114]
In the Parameter Exploration section the code fails if one increases _inh_rate_ variable too much. As the result there are no spikes and this results in "ValueError: zero-size array to reduction operation minimum which has no identity" when computing distribution statistics (_amin function). If this was not left on purpose I'm afraid this may confuse some students.
Details are on a screen-shot below.
![Too_strong_inhibition](https://user-images.githubusercontent.com/48945883/85651561-d2373c00-b6c1-11ea-9425-65af626e265b.png)
.

**Comment by felenitaribeiro** [comment]
Video 6 and 7 are missing (assuming they exist, as the only video available is Tutorial 8, and the previous notebook has 5 videos).
