### ISSUE TITLE
W1D1T3 - Explaining the difference in conditions between penultimate and last example

### ISSUE THREAD

**Issue by Visdoom** [NeuromatchAcademy/course-content#165]
Hey there, 
Maybe more a comment than anything major, but something I stumbled over: 
The simulated part leaves off with the impression that exponential ISI distributions should yield most entropy (when the mean is fixed) but then in the interactive tool the "uniform" neurons show the higher entropies. 
I think a sentence or two that point out the different conditions would be helpful.

**Comment by felenitaribeiro** [comment]
Yeah, agree! That felt strange to me too. Also, I found a typo... In the 'Optimization and Information' section, you missed an R in 'Shannon int**R**oduced'.

**Comment by msarvestani** [comment]
Thanks both. These have been resolved.
