### ISSUE TITLE
W2D2 - Tutorial 1

### ISSUE THREAD

**Issue by SeeebO** [NeuromatchAcademy/course-content#179]
In the helper function 
'plot_trajectory(system, params, initial_condition, dt=0.1, T=6, figtitle=None)': 

`solution = solve_ivp(system, 
                     t_span=(0, T), 
                     y0=x0, t_eval=t, 
                     args=(params),
                     dense_output=True)`

v0 is set to x0, but the argument passed to the helper function is 'initial_condition'

**Comment by mrkrause** [comment]
Will be fixed in #276
