### ISSUE TITLE
Case consistency in repo

### ISSUE THREAD

**Issue by mpbrigham** [NeuromatchAcademy/course-content#19]
What case policy should we adopt for this repo?

**Comment by patrickmineault** [comment]
For Python? PEP8.

**Comment by mpbrigham** [comment]
Sounds good. What about file and folder names?

**Comment by patrickmineault** [comment]
Lower case for folder names, snake case for python files and markdown,
first letter in caps for ipython notebooks (with spaces in the filename).

**Comment by patrickmineault** [comment]
It would be good to write this up in the notebook review guide.

**Comment by mpbrigham** [comment]
Implemented here:
https://github.com/NeuromatchAcademy/course-content/pull/21
