### ISSUE TITLE
W1D2T1- Missing illustration of conditions?

### ISSUE THREAD

**Issue by Visdoom** [NeuromatchAcademy/course-content#190]
When I load the tutorial I get this 
![image](https://user-images.githubusercontent.com/520137/86292988-0ba40600-bbf2-11ea-8592-a0a45069bcb5.png)

Is there an image missing?

**Comment by mwaskom** [comment]
Hi @Visdoom thanks for reporting. Can you please say which tutorial this is for?

**Comment by Visdoom** [comment]
sorry, forgot that part!

**Comment by msarvestani** [comment]
Thanks. This has been resolved in the final tutorials.
