### ISSUE TITLE
W1D2T2 - Micro-tutorial 7

### ISSUE THREAD

**Issue by felenitaribeiro** [NeuromatchAcademy/course-content#197]
Just a detail that was a bit confusing... In Micro-tutorial 7, in the step-by-step, it says after filtering to take the average, even though it is to take the final value. 

![TD7 1](https://user-images.githubusercontent.com/33485379/86307803-07600300-bc5b-11ea-8575-0fcfb143bdd0.png)

**Comment by msarvestani** [comment]
Good catch! This has been fixed in the final notebooks.
