### ISSUE TITLE
Bug in W1D3 Tutorial 7 solution

### ISSUE THREAD

**Issue by kdoelling1919** [NeuromatchAcademy/course-content#199]
https://github.com/NeuromatchAcademy/course-content/blob/c0b0fcdd7e6d9d6ab1f50c6d0280e9011723ae4b/tutorials/W1D3_ModelFitting/solutions/W1D3_Tutorial7_Solution_cf15e1ca.py#L17

At the linked line, the code calculates AIC using `n_samples`.

However, in the previous cell (show below), `n_samples` is last defined for the test dataset.
```python
# You've seen this code before!

### Generate training data
np.random.seed(0)
n_samples = 50
x_train = np.random.uniform(-2, 2.5, n_samples) # sample from a uniform distribution over [-2, 2.5)
noise = np.random.randn(n_samples) # sample from a standard normal distribution
y_train =  x_train**2 - x_train - 2 + noise

### Generate testing data
n_samples = 20
x_test = np.random.uniform(-3, 3, n_samples) # sample from a uniform distribution over [-2, 2.5)
noise = np.random.randn(n_samples) # sample from a standard normal distribution
y_test =  x_test**2 - x_test - 2 + noise

### Fit polynomial regression models
max_order = 5
theta_hat = solve_poly_reg(x_train, y_train, max_order)
```
 It's the training dataset that's being used to calculate AIC and as the training set is larger, it results in an inaccurate AIC (though it doesn't affect model selection).

Solution:
either 
1. replace `n_samples` in the line with `len(y_hat) or
1. use the test dataset for AIC calculation.

This will also require redoing the solution figure for this cell in the tutorial 7 notebook.

**Comment by ebatty** [comment]
Thanks for noting!! This will be fixed in final release
