### ISSUE TITLE
Proposal on information displayed

### ISSUE THREAD

**Issue by titipata** [NeuromatchAcademy/course-content#2]
Maybe something like the following is easier to read? @patrickmineault @GunnarBlohm 

## Mon, July 13: Introduction to Computational Neuroscience and NMA

**Description** Introduction of datasets (spikes, EEG, fMRI + behavior), and questions about them. These questions will foreshadow the whole summer school.

### Day 1 Schedule

| Time (Hour)        | Lecture                          | Detail                                                             |
|-------------|----------------------------------|--------------------------------------------------------------------|
| 0:00 - 0:50 | Intro / keynote & tutorial setup | NMA organization, expectations, code of conduct, modeling vs. data |
| 1:30 - 2:05 | Lecture & Tutorial 1             | Data intro, preprocessing                                          |
| 2:10 - 2:45 | Lecture & tutorial 2             | Link of neural data to behavior 
| 4:35 - 5:30 | Recap, Q&A | Outlook on school |
| 5:30 - 6:00 | Professional development | Being a good NMA participant |

**Comment by GunnarBlohm** [comment]
The only reason I didn't go with that is bc it gets very long! But if you want to change it, fee l free!
