### ISSUE TITLE
Content problem with Week 1, Day 4, Tutorial 1

### ISSUE THREAD

**Issue by Anindita94-bit** [NeuromatchAcademy/course-content#200]
Exercise: Predict spike counts with Linear-Gaussian model
After running this chunk of command it's showing "stem() got an unexpected keyword argument 'use_line_collection'"

**Comment by mwaskom** [comment]
How are you running the tutorial? That parameter was added in matplotlib 3.1. It's available on colab, but if you're trying to run in a different environment you may have to update you matplotlib.

**Comment by Anindita94-bit** [comment]
For better understanding, I am running these codes in python 3 of Jupyter
notebook using Anaconda 3.
Do I need an updated version?

Thanks,
Anindita

**Comment by Anindita94-bit** [comment]
I think this problem is related to the version of python I am using as in Colab it's running properly.
Thanks

**Comment by mwaskom** [comment]
It's not the version of python, it's the version of matplotlib.

**Comment by Anindita94-bit** [comment]
Yes, now I have understood, I think it's required matplotlib.pyplot.stem to
be updated. Sorry to bother you about this.

Thanks,
Anindita

Best regards,
Anindita Bhattacharjee
Ph.D. Research Scholar
School of Biomedical Engineering
IIT-BHU, Varanasi, INDIA
221005
