### ISSUE TITLE
W2D3 youtube playlist is wrong

### ISSUE THREAD

**Issue by JesseLivezey** [NeuromatchAcademy/course-content#202]
The playlist for W2D3 here
https://github.com/NeuromatchAcademy/course-content/tree/master/tutorials#w2d3---decision-making
links to the W3D3 playlist

**Comment by mwaskom** [comment]
Thanks @JesseLivezey. Could you submit a fix? You can just edit the file on github.

**Comment by JesseLivezey** [comment]
@mwaskom Is there a list of links somewhere? The playlists seem to be unlisted on the youtube channel, so there's no way to navigate to the correct one.

**Comment by mwaskom** [comment]
They're on our content review signup google doc, here's W2D3: https://www.youtube.com/playlist?list=PLkBQOLLbi18P7P535AyvKGEGWRQtTMH-Y
