### ISSUE TITLE
W1D3T1 - Wrong equation

### ISSUE THREAD

**Issue by felenitaribeiro** [NeuromatchAcademy/course-content#204]
When you analytically minimize MSE in the notebook, the result should be sum(x*y)/sum(x*x) as in the video, and not sum(x*y/x**2)
![W1D3](https://user-images.githubusercontent.com/33485379/86417537-a2ff7b00-bd10-11ea-9685-a6f6cc6442e7.png)

**Comment by ebatty** [comment]
Hello! Thanks so much for caring and commenting! In this derivation, we are assuming that y and x are 1D (single regressor and single output) so it is correct as is
