### ISSUE TITLE
W3D5T2 not rendering properly on nbviewer

### ISSUE THREAD

**Issue by mpbrigham** [NeuromatchAcademy/course-content#210]
The nbviewer badge for for T2 lands on `400 : Bad Request` and displays a plotly dictionary. Any ideas?

**Comment by mwaskom** [comment]
That is weird. I don't use plotly much so I don't know if this is a known issue. It does sound like plotly graphs fail to render in at least some static contexts. I was going to suggest reworking those plots to use matplotlib anyway since we wanted to avoid the overhead of a new library. Would that be alright?

**Comment by mpbrigham** [comment]
It's also the 1st time I've encountered this problem - renders well on jupyter. github but not on nbviewer.

I totally agree that if we could display interactive 3D plots with matplotlib providing the same user experience as with plotly then we should go for that and avoid the hassle of an additional library. To my knowledge, 3D experience with matplotlib feels clunky but I'm not an expert.

Seeing it from the student's perspective:
- fluid and interactive 3D plotting has a wow factor that homes in the message clearly and is sure to bleed into their future projects (just a few lines of code after all)
- this is the last day of the course and they see an alternative to matplotlib

What do you think?

**Comment by mwaskom** [comment]
We've made a couple of other CCs remove some higher-level libraries to keep things running on the defined environment with minimal extra installs. If you think it's pedagogically important, it can be fine. FWIW I find the allure of interactive plots wears off pretty quickly...  But actually, in trying to gauge how useful the plots are, I ran the instructor version and I'm not sure it's doing the right thing? This is a screenshot of what the second 3D plot (which I gather is meant to show points on the surface of a sphere) looks like for me:

![image](https://user-images.githubusercontent.com/315810/86488222-4c089e80-bd2e-11ea-8228-c51b4e05ca71.png)

**Comment by mpbrigham** [comment]
Weird, this is what I get when running the colab version:
![image](https://user-images.githubusercontent.com/8041737/86489264-b84dc700-bd5b-11ea-92f4-038791d24852.png)

**Comment by mpbrigham** [comment]
Yes, something seems off with the github version.

**Comment by mpbrigham** [comment]
I see the problem: the latent space coords cannot be cast to integer. This is the proper call:
`plot_latent_3d(latent_test, y_test.int())`

**Comment by mpbrigham** [comment]
OK, the same problem is also happening with W2D5T2:
https://nbviewer.jupyter.org/github/NeuromatchAcademy/course-content/blob/master/tutorials/W2D5_ReinforcementLearning/W2D5_Tutorial2.ipynb

**Comment by mwaskom** [comment]
Fixed now that notebooks are stored without outputs.
