### ISSUE TITLE
W1D4T1 - Wrong equation

### ISSUE THREAD

**Issue by felenitaribeiro** [NeuromatchAcademy/course-content#217]
In the notebook the log-likelihood is given like this for Poisson GLM:

![W1D4T1](https://user-images.githubusercontent.com/33485379/86503897-cf40f780-bdf5-11ea-972d-b60af18bfdd1.png)

inducing to the wrong answer in the exercise.

But in the video it is:

![W1D4T1_2](https://user-images.githubusercontent.com/33485379/86503899-d7009c00-bdf5-11ea-9916-f1043a1a26b0.png)

which is the correct one.

**Comment by msarvestani** [comment]
Please see Video 1, slide 6 (2:50 timestamp and onwards) for clarification. The differences are due to changes in notation between the vector form and matrix form of these equations. For in stance, the order of the variables theta and x change from vector format to matrix format.

**Comment by mwaskom** [comment]
I think the original issue is about the fact that the prepod notebook was missing the nonlinearity. I believe this has been fixed in the final version. Sorry, I should have checked for issues to close while finalizing W1D4.

**Comment by msarvestani** [comment]
Oh I see! That makes more sense. Ok will close this out then.
