### ISSUE TITLE
W2D2_Tutorial3 wrong equilibrium variance equation in Part C

### ISSUE THREAD

**Issue by yhz-1995** [NeuromatchAcademy/course-content#219]
In part C of W2D2_Tutorial3 the equilibrium variance of the OU process is calculated as:
`Var = sig^2 / (2*(1-lambda))`

However, I think that this is not the correct analytical solution of the equilibrium variance. A simple mathematical prove (for equabilirum mean=0) is shown below (the `~` sign means "follows the distribution"):
```
x0 = x0
x1 = lambda*x0 + N(0, sig^2) ~ N(lambda*x0, sig^2)
x2 = lambda*x1 + N(0, sig^2) ~ lambda*N(lambda*x0, sig^2) + N(0, sig^2) ~ N(lambda^2*x0, (lambda^2+1)*sig^2)
x3 = lambda*x2 + N(0, sig^2) ~ N(lambda^3*x0, (lambda^4+lambda^2+1)*sig^2)
.
.
.
xn ~ N(lambda^n*x0, (lambda^(2*n-2) + ... + lambda^4+lambda^2+1)*sig^2)
```
Note that:
```
lambda^(2*n-2) + ... + lambda^4+lambda^2+1 = (1-lambda^(2*n)) / (1-lambda^2)
```
And since `lambda < 1`, `n -> inf`, so `lambda^(2*n) -> 0`, therefore:
```
lambda^(2*n-2) + ... + lambda^4+lambda^2+1 = 1 / (1-lambda^2)
```
Therefore, 
```
xn ~ N(lambda^n*x0, sig^2/(1-lambda^2))
```
So the equilibrium variance should be `sig^2/(1-lambda^2)` instead of `sig^2/(2*(1-lambda))`
And if you use this new analytical solution in exercise 3C, you can find that the fit to diagonal line is better.

**Comment by mrkrause** [comment]
Fixed, thanks!
