### ISSUE TITLE
Implementing case consistency in repo

### ISSUE THREAD

**Issue by mpbrigham** [NeuromatchAcademy/course-content#22]
When would it be a good time to implement case consistency across the repo?

Some direct links have been shared on social media, like for example:
`https://github.com/NeuromatchAcademy/course-content/tree/master/tutorials/reviewing-tutorials.md`

This markdown file should be named `ReviewingTutorials.md` following the new guidelines.

**Comment by patrickmineault** [comment]
Solved by pull request, closing.
