### ISSUE TITLE
Video links in PythonWorkshop

### ISSUE THREAD

**Issue by zuxfoucault** [NeuromatchAcademy/course-content#229]
The video links in PythonWorkshop link to video Bayesian Statistics Day, will this part be replaced soon? Or there's no video for the workshop?

**Comment by mwaskom** [comment]
I believe there will be videos for the Python Workshop, but they aren't ready yet.

**Comment by mpbrigham** [comment]
@zuxfoucault here is the Youtube playlist for Day 1 of Python workshop:
https://www.youtube.com/playlist?list=PLkBQOLLbi18OOfG3REOQrAFv8sRsHt9Y-

**Comment by mwaskom** [comment]
@mpbrigham we need to get that link in https://github.com/NeuromatchAcademy/course-content/blob/master/tutorials/youtube_playlists.txt so it will be picked up by the README generator

**Comment by mwaskom** [comment]
Can do it as we ship the final W0D1 Python.

**Comment by zuxfoucault** [comment]
Close this issue?
