### ISSUE TITLE
Code cells not hidden in local jupyter notebook

### ISSUE THREAD

**Issue by jerlich** [NeuromatchAcademy/course-content#230]
I think the cells with `import ....` (and some function definitions)  are intended to be hidden by default, but when cloning the repo, installing the dependencies using conda and then running `jupyter notebook` the cells are not hidden.

**Comment by mwaskom** [comment]
Yeah, the code hiding is using a colab-only feature. Unfortunately, there is no analogous functionality in Jupyter itself.

**Comment by jerlich** [comment]
No problem. it's not a huge deal. (and we are shipping in a few days). But for future reference, why doesn't this work:
https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/hide_input/readme.html

**Comment by mwaskom** [comment]
I think each student would need that extension installed locally? Or have it installed on whatever non-colab hosted system (e.g. binder) they are using? I haven't looked closely.  Jupyter extensions are a little brittle, so I would be wary about relying on them, but I'm not firmly opposed. Another wrinkle is that the Colab interface doesn't expose any access to the Jupyter tag metadata that extensions like these depend on, so setting it up would require another step of editing in a local interface.

**Comment by jerlich** [comment]
definitely not worth it for this year, but maybe we can look into it for the future. From my browsing of the nbextenstions, it would be possible to just put a `setup.sh` in the repo that did everything:
1. make sure conda is installed
2. create an environment based on the yaml
3. installed the necessary jupyter extensions
