### ISSUE TITLE
W1D1 tutorial 1 section 3 exercise 2

### ISSUE THREAD

**Issue by i-am-mel-dev** [NeuromatchAcademy/course-content#241]
Below an issue which may be understood politically wrong... maybe retyping the parameter as ISIs would change the understanding?
![image (1)](https://user-images.githubusercontent.com/17802601/87046208-86c47800-c201-11ea-82e8-abe92829cd3f.png)

**Comment by i-am-mel-dev** [comment]
reading as 'eye-es-eyes' as suggested makes sense since ISIs is the well known convention.

**Comment by mwaskom** [comment]
Thank you @i-am-mel-dev for your careful eye on our tutorials! As we discussed in Slack, the political resonance of this term is unfortunate, but it has a very long-standing usage in neuroscience and we would not want to invite confusion by inventing a different term. We will perhaps revisit the question of, changing the capitalization next year when we would have time to rerecord the relevant videos and modify the notebooks. For this year, we strongly encourage everyone to refer to the term as an initialism (eye-ess-eyes), which is the convention in neuroscience.
