### ISSUE TITLE
W0D2 Wrong class variable

### ISSUE THREAD

**Issue by NeoNeuron** [NeuromatchAcademy/course-content#242]
https://github.com/NeuromatchAcademy/course-content/blob/a35045a706b9780d11a680da7bd3c79e5f901b91/tutorials/W0D2_PythonWorkshop2/solutions/W0D2_Tutorial1_Solution_f9a049ea.py#L52

In the solution script of Exercise 7 in the notebook of W0D2, the line referred above should be corrected as
```
clamped = (self.last_spike + self.t_ref > t) 
```
Otherwise, the class function will access the global variable `t_ref` which does not belong to the NeuralSimulator class, and lead to incorrect result.

**Comment by mpbrigham** [comment]
Good catch @NeoNeuron! Copy-pasta always gets the best pf me. ;-)
Corrected in the updated version.
