### ISSUE TITLE
Put a "DRAFT VERSION: this content is not finalized" into not done notebooks

### ISSUE THREAD

**Issue by jerlich** [NeuromatchAcademy/course-content#254]
It is likely that people will browse ahead of the schedule (especially non-interactive track people).

Seems prudent to warn them that the content is not finalized.

**Comment by mwaskom** [comment]
We had a long discussion about this yesterday (last night) in slack. I hope to resolve it today. There were three options 1) remove unfinished days from the master branch 2) annotate unfinished days in the README 3) modify the notebooks themselves. I prefer (2) but it is trickier to implement, so it is likely that (3) will be what happens.

**Comment by mwaskom** [comment]
One problem with this specific suggestion is that it is likely to create merge conflicts with the notebooks that currently have an open PR.

Given that each solution has its drawbacks, we will likely prioritize shipping the first week of content, which will help to obviate the underlying problem.

**Comment by jerlich** [comment]
A statement in the readme like “Content is being finalized 1-2 days before it is covered in the syllabus, so be warned that trying to run notebooks ahead of schedule may have issues / incorrect videos linked etc”. This would remain true and not have to be regularly updated.
