### ISSUE TITLE
W0D1 Exercise 8

### ISSUE THREAD

**Issue by mwaskom** [NeuromatchAcademy/course-content#256]
From @rshpeley in #243

This exercise is meant to replicate exercise 7 but using numpy arrays in place of python lists. The solution for exercise 7 and its graph shows all 150 points are plotted. This solution plots 149 points and misses the first one. You'll see this visually in comparing the 2 graphs.

The recommended code changes increase the size of the v array by one to accommodate the last calculated update to v and slices v back to size before plotting:

```diff
 # set random number generator
 np.random.seed(2020)

 # initialize step_end, t_range, v and syn
 step_end = int(t_max / dt)
 t_range = np.linspace(0, t_max, num=step_end)
-v = el * np.ones(step_end)
+v = el * np.ones(step_end + 1)
 syn = i_mean * (1 + 0.1 * (t_max/dt) ** (0.5) * (2 * np.random.random(step_end) - 1))

 # loop for step_end - 1 steps
-for step in range(1, step_end):
+for step in range(step_end):

-  v[step] = v[step - 1] + (dt / tau) * (el - v[step - 1] + r * syn[step])
+  v[step + 1] = v[step] + (dt / tau) * (el - v[step] + r * syn[step])

 with plt.xkcd():
   # initialize the figure
@@ -20,5 +19,5 @@ with plt.xkcd():
   plt.xlabel('time (s)')
   plt.ylabel(r'$V_m$ (V)')

-  plt.plot(t_range, v, 'k.')
+  plt.plot(t_range, v[:-1], 'k.')
   plt.show()
```

**Comment by rshpeley** [comment]
I tried a new pull request of this issue, modifying W0D1_Tutorial1.ipynb, in #260 and got this error:
``` shell
Push post-processed notebooks1s
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
Run ad-m/github-push-action@v0.6.0
Started: bash /home/runner/work/_actions/ad-m/github-push-action/v0.6.0/start.sh
Push to branch rshpeley-jul-11-2020
remote: Permission to NeuromatchAcademy/course-content.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/NeuromatchAcademy/course-content.git/': The requested URL returned error: 403
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/v0.6.0/start.js:9:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/v0.6.0/start.js:9:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```
I presume it's a matter of permissions, but if it's related to a requirement on my part I'd like to find out what to do differently.

Whenever someone has time, could you look into this?

**Comment by mwaskom** [comment]
Sorry @rshpeley it might be that the CI workflow fails when people don't have commit rights on the repository. That would surprise me, but it is possible. Unfortunately we are completely swamped on finalizing the content for the days that are ahead of us, and so improvements to days we have already passed will have to wait.

In general I think we would prefer that students/TAs just raise issues about problems they run into. It's great that you took the initiative to suggest a fix and to do it in a PR. But we want to keep the original content creators in the loop on potential changes to their tutorials, and most don't look closely at the Github, so I'm afraid the PR might linger for a while.

**Comment by rshpeley** [comment]
Yeah, sounds very reasonable. I've found a related issue for exercise 12 plus missing content for enumerate in the Numpy video: "Using Numpy". I'm just wondering what I should do with these now. I don't want to continue taking up your's or other's attention when you need to work on course content. Maybe just wait and I'll post these later? 

btw, so far I've found the content very useful and I'm looking forward to the course. You people are doing a great job!

**Comment by JesseLivezey** [comment]
@rshpeley definately make an issue for problems you find!

**Comment by mwaskom** [comment]
Yes, please open issues as you encounter them!

**Comment by rshpeley** [comment]
Please close this issue. I'll soon be providing a corrected and more extensive pull request.
