### ISSUE TITLE
W1D1 Interactive Demo: ISI functions explorer, 1 exp parameter could be removed

### ISSUE THREAD

**Issue by JesseLivezey** [NeuromatchAcademy/course-content#273]
```python
ys = scale * np.exp(rate * (xs - x0))
```
could just be
```python
ys = np.exp(rate * (xs - x0))
```
and have the same flexibility.

**Comment by ebatty** [comment]
This is true, but I think we should leave it as is to be consistent with the videos (otherwise those show an extra parameter)
