### ISSUE TITLE
Link to Curated Datasets Playlist is off under project content

### ISSUE THREAD

**Issue by Visdoom** [NeuromatchAcademy/course-content#283]
When clicking the Curated Datasets link [here](https://github.com/NeuromatchAcademy/course-content/blob/master/projects/README.md) it brings me to a playlist were overview, instructions, and brainstorming videos are in the wrong order and the overview video is in there twice https://www.youtube.com/playlist?list=PLkBQOLLbi18ODTckxhgah98JloMLXt4oF. 
I recommend to either remove the link here or get the videos in the right order.

**Comment by mwaskom** [comment]
It looks like this has been fixed. Please ping if you disagree.
