### ISSUE TITLE
Replace wget with requests in notebooks. 

### ISSUE THREAD

**Issue by mrkrause** [NeuromatchAcademy/course-content#285]
These notebooks use still !wget, rather than requests, which makes their output less deterministic

- ~~./projects/load_stringer_orientations.ipynb~~
- ~~./projects/load_stringer_spontaneous.ipynb~~
- ~~./projects/load_kay_images.ipynb~~
- ~~./projects/load_steinmetz_decisions.ipynb~~
-  ~~./tutorials/W2D3_DecisionMaking/W2D3_Tutorial3.ipynb~~
-  ~~./tutorials/W3D5_DeepLearning2/W3D5_Tutorial3.ipynb~~
-  ~~./tutorials/W3D5_DeepLearning2/W3D5_Tutorial1.ipynb~~
- ~~./tutorials/W3D4_DeepLearning1/W3D4_Tutorial3.ipynb~~
- ~~./tutorials/W3D4_DeepLearning1/W3D4_Tutorial1.ipynb~~
- ~~./tutorials/W3D4_DeepLearning1/W3D4_Tutorial2.ipynb~~
-  ~~./tutorials/W3D3_NetworkCausality/W3D3_Tutorial3.ipynb~~
- ~~./tutorials/utils/Installing Python libraries.ipynb~~
-  ~~./tutorials/W1D2_ModelingPractice/W1D2_Tutorial1.ipynb~~
-  ~~./tutorials/W1D2_ModelingPractice/W1D2_Tutorial2.ipynb~~

**Comment by spirosChv** [comment]
fixed during the post fixes process.
