### ISSUE TITLE
W1D1 T1 percent signs are used with fractions

### ISSUE THREAD

**Issue by JesseLivezey** [NeuromatchAcademy/course-content#292]
The fraction of neurons are computed as fractions, but printed with a percent sign, so ".33%" should be "33%" or just ".33".

**Comment by da5nsy** [comment]
Looks like this is taken care of by the formatting (admittedly in a way that I don't fully understand - see https://stackoverflow.com/a/57150518/6464224)

Compare:
```
print(f"{frac_interval_spikes:.2%} of the total spikes are in the interval")
print(f"{frac_interval_spikes:.2} of the total spikes are in the interval")
```

**Comment by mwaskom** [comment]
I think this is correct. The selected interval is 10 s long and the experiment is about 2700 s long (based on maximum spike time). Which is 0.003700962250185048 or 0.037%.

> admittedly in a way that I don't fully understand

Python string formatting accepts `%` as a formatting code (like `f` for floating point truncation or `g` for scientific notation) that does the x 100 computation internally.

@JesseLivezey if you agree, please close.

**Comment by JesseLivezey** [comment]
Good catch! I didn't know about the % formatting!
