### ISSUE TITLE
W1D1 Tutorial 2 does not set a random seed

### ISSUE THREAD

**Issue by mwaskom** [NeuromatchAcademy/course-content#295]
But the exercises use random numbers, so it's not possible to exactly reproduce the example hint images.

(The exercises use `scipy.stats` to generate from a poisson distribution, but that reads from the global numpy RNG, so setting the seed the same way will work).

**Comment by da5nsy** [comment]
This came up in my pod also.
There is certainly an argument for actively _not_ fixing this - it is good to show that there is some randomness involved.
For the record though, I lean towards adding a random seed.

A compromise solution might be to add a comment which discusses this.

**Comment by mwaskom** [comment]
At least one of the tutorials (I forget which) has a comment on the random seed that suggests commenting it out and seeing how the result changes when you rerun multiple times. But we should always make it possible to exactly reproduce the example solution image.

**Comment by da5nsy** [comment]
The W1D3 tutorials have a seed. This for me adds to the argument that the W1D2 ones should have a seed.
