### ISSUE TITLE
W0D2_Tutorial1, bug while defining function plot_all()

### ISSUE THREAD

**Issue by SidongWang** [NeuromatchAcademy/course-content#300]
Within the third cell under the 3 Setup title, while defining function plot_all(), at line 46: <br>

    plt.scatter(t_range, v_n[j], color="k", marker=".", alpha=0.01)

here variable `v_n` is neither an input variable nor a variable defined in the function, therefore it must be a typo for `v`. It works fine in this notebook, but won't function normally if `v_n` doesn't exist or is not equal to the input of the function.

**Comment by mpbrigham** [comment]
Excellent, thank you so much @SidongWang. That bug was spotted and corrected in an earlier version, but apparently didn't make it to the final version. Please keep us posted on any other issue you may come across.

**Comment by mwaskom** [comment]
@mpbrigham OK to close?
