### ISSUE TITLE
W1D2 nbviewer showing old version which does not match colab

### ISSUE THREAD

**Issue by mmyros** [NeuromatchAcademy/course-content#301]
Related to https://github.com/NeuromatchAcademy/course-content/issues/210 ?

**Comment by mwaskom** [comment]
Both tutorials render fine for me. What are you seeing?

**Comment by mmyros** [comment]
I think an old version

**Comment by mmyros** [comment]
e.g. 

`# Create Expectations
###################################################################
## Change the values in the lists below. 
## These act as X and Y coordinates for a scatter plot, 
## so make sure the lists match in length.
## the provided code will plot your expectations
################################################################### 

#To complete the exercise, uncomment the code below and fill in the missing parts (?)

#world_vel_exp = [0, 1, ?, ?]
#self_vel_exp  = [?, ?, 0, 1]

#expectations = {'world':world_vel_exp, 'self':self_vel_exp}
#my_plot_percepts(datasets={'expectations':expectations})`

This is different in Colab

**Comment by mwaskom** [comment]
Oh, #210 is describing a different issue where the rendering totally fails and the nbviewer page is just garbage.

If the nbviewer and colab content don't match, this is likely a caching problem, not a rending problem. nbviewer is notorious for being sluggish to reflect changes in the underlying file (e.g. follow rabbit trail of issues from [here](https://github.com/jupyter/nbviewer/issues/914).

**Comment by mmyros** [comment]
I'll try flush_cache in my fork and report back

**Comment by mwaskom** [comment]
Fixed by #302 (But please comment if you run into the issue again, as `flush_cache=true` is reported to be unreliable.

**Comment by mmyros** [comment]
More problems. Maybe we should find a different solution or remove links to nbviewer

**Comment by mmyros** [comment]
Why not link to ipynb file in github? maybe it will be sometimes broken, but obviously so

**Comment by mwaskom** [comment]
In my experience, github version successfully renders <20 % of our tutorials. Also github renders the math really poorly.
