### ISSUE TITLE
Notebook spacing standard

### ISSUE THREAD

**Issue by mpbrigham** [NeuromatchAcademy/course-content#31]
Should we adopt the usual spacing in Jupyter notebook (4 spaces) or Colab's 2 spaces?

**Comment by patrickmineault** [comment]
Colab's two since we're advising authors to stay in colab as long as possible.

**Comment by mpbrigham** [comment]
Would this recommendation go into `writing-tutorials.md` and `reviewing-tutorials.md`?

**Comment by mpbrigham** [comment]
see https://github.com/NeuromatchAcademy/course-content/pull/36
