### ISSUE TITLE
Some minor issues with W1D2 content

### ISSUE THREAD

**Issue by lingqiz** [NeuromatchAcademy/course-content#312]
1. The y-axis is confusing in Tutorial 1, TD 3.2 (It should be just **proportion classified as self-motion**).
2. In the text immediately below, it should read "in the self-motion condition **(orange line)** we should always detect self-motion, and is never in the world-motion condition **(blue line)**".
3. In Tutorial 2, function ``my_train_illusion_model``, header comment, it says 
> filterwindow: (list of int) determines the strength of filtering for the **visual and vestibular signals, respectively**

However, in the code below, we treat the first entry ``filterwindow[0]`` as the window size for vestibular signals, and the second entry ``filterwindow[1]`` as the window size for visual signals.

**Comment by gumadeiras** [comment]
additionally, the rest of the tutorial assumes the key name in params to be ‘filterwindows’ (plural)
