### ISSUE TITLE
Please dont remove content right before tutorials!!

### ISSUE THREAD

**Issue by mmyros** [NeuromatchAcademy/course-content#323]
I dont know what commit it was, but the derivation for OLS disappeared as I was working on it!!

**Comment by mwaskom** [comment]
It would be helpful if you could be more specific about what happened. Even if the content on github changes, I don't think Colab will refresh to reflect that?

**Comment by ebatty** [comment]
Also when did this happen? Just now?

**Comment by mmyros** [comment]
Arrrgh it's the nbviewer

**Comment by mmyros** [comment]
Thanks for the comments sorry about the stress. Dont use nbviewer

**Comment by mwaskom** [comment]
Did it actually reload on you, though?
