### ISSUE TITLE
W1D3 tutorials - solutions use `with plt.xkcd():`

### ISSUE THREAD

**Issue by da5nsy** [NeuromatchAcademy/course-content#326]
In previous tutorials the `with plt.xkcd():` was reserved to show the difference between the auto-filled examples and things actually generated by the written code. 
Sometimes when things break or you want to double check things it is nice to be able to copypaste the whole code chunk, and it is confusing when the output plots are in xkcd style.

*Proposed fix*: remove xkcd style from solutions in https://github.com/NeuromatchAcademy/course-content/tree/master/tutorials/W1D3_ModelFitting/solutions

---

I'm happy to do this but want clarification that this won't mess up the static components before I go in and meddle with code.

**Comment by mwaskom** [comment]
These are auto-generated by extracting the cells that exist in the instructor notebooks. So modifying the existing code would not be persistent after future changes to the source files.

It would be theoretically possible to to detect and remove this during the automated notebook creation, but it would essentially require parsing the Python (not just the text) or making a variety of assumptions about the structure of the code. This is maybe something to consider for V2, but it should not happen while the course is live.

**Comment by mwaskom** [comment]
I'm a bit confused by where you say "In previous tutorials...". Did W1D3 not carry on this convention?

**Comment by da5nsy** [comment]
Ah my apologies, I appear to be mistaken - I thought that in W1D2 the solutions files didn't have the xkcd styles. I must not have copied the whole thing yesterday.

I had assumed that is was just this set of tutorials that was out of kilter.

**Comment by mwaskom** [comment]
Anywhere `plt.xckd` made the solution, it will appear in the solution files. We occasionally omit it from the solution hint image itself, as there are some styles of plot that xkcd mode renders unintelligible.

**Comment by da5nsy** [comment]
Cool, all good, my misunderstanding. Thanks for clearing up.
