### ISSUE TITLE
W1D3 missing variable in solution 

### ISSUE THREAD

**Issue by da5nsy** [NeuromatchAcademy/course-content#328]
The [solution file for W1D3_Tutorial5 compute_mse](https://github.com/NeuromatchAcademy/course-content/blob/master/tutorials/W1D3_ModelFitting/solutions/W1D3_Tutorial5_Solution_d7a57567.py) is missing the `width` parameter (defined as `width = .35`) in the template.

**Comment by mwaskom** [comment]
Fixed.
