### ISSUE TITLE
W1D4 Tutorial 1 Exercise 3 last equation

### ISSUE THREAD

**Issue by arashash** [NeuromatchAcademy/course-content#337]
the last equation has extra transpose which doesn't match the code and was a source of confusion during my pod.

**Comment by mwaskom** [comment]
Hi @arashash when you report issues like these, can you please be very clear about a) exactly what it says in the version of the notebook you're looking at and b) exactly what you think it should say? We are working on a set of contributing guidelines but in general, the more context and information you can provide, the more helpful your report will be.

**Comment by arashash** [comment]
Hi @mwaskom. sure thing. so where my mouse is pointing there is X^T but it should be just X, otherwise, the inner dimension won't match
![image](https://user-images.githubusercontent.com/15813444/87851135-9416ec00-c8fe-11ea-8702-2fda04963894.png)
