### ISSUE TITLE
W1D5T4 Ex1 overwriting of variables

### ISSUE THREAD

**Issue by robbisg** [NeuromatchAcademy/course-content#353]
```python
# This is the solution
X, labels = X[:2000, :], labels[:2000]
# Perform PCA 
scores = pca_model.transform(X)
# Plot the data and reconstruction
with plt.xkcd():
  visualize_components(scores[:, 0], scores[:, 1], labels)
```

If you run this cell several times (as I did since I saw 200 instead of 2000), ```X``` and ```labels``` are overwritten so I think it's better to rename them!

**Comment by mwaskom** [comment]
I'm confused, why were you running the solution code multiple times?

**Comment by mwaskom** [comment]
(I agree in general that calling them `X_crop` or similar would make sense.

**Comment by robbisg** [comment]
Yep, because it may happen that you want to run the cell with more or less samples!

**Comment by mwaskom** [comment]
Right but I'm confused, you're showing the solution code, which is unrunnable. How much of that is in the exercise cell itself?

**Comment by robbisg** [comment]
I'm sorry I didn't explain it.
This is the code in the notebook
```python
#################################################
## TODO for students: take only 2,000 samples and perform PCA
#################################################

# Take only the first 2000 samples with the corresponding labels
# X, labels = ...
# Perform PCA 
# scores = pca_model.transform(X)

# Plot the data and reconstruction
# visualize_components(...)
```
I think that students do not rename variables!

**Comment by mwaskom** [comment]
Got it. Yes, I think that going forward providing a new name in the given code will be better. Or students can do `X.copy()[:2000]` :)

**Comment by mwaskom** [comment]
Actually, I do think downstream cells expect that the data have been cropped (otherwise tSNE will take forever) so that's important to keep in mind.

**Comment by robbisg** [comment]
Yep, my suggestion is to use different names when loading the data (e.g. data, labels) and other names when they are cropped (e.g. X, y).
