### ISSUE TITLE
Dimensionality Reduction T1 - calculate_cov_matrix invalid parameters

### ISSUE THREAD

**Issue by FedeClaudi** [NeuromatchAcademy/course-content#354]
Hi, 

In W1D5T1, exercise 1, the function `calculate_cov_matrix` takes `corr_coeff` as argument which should be in range [-1,1].
If a values of `corr_coeff` is passed that is outside this range, the exercise cell runs without error but the plot is generated with the last valid `corr_coeff` given. 

This might be confusing, I think  `calculate_cov_matrix` should throw an error if `corr_coeff` is not in the correct range, or at the very least it should not produce a plot.

**Comment by mwaskom** [comment]
Thanks @FedeClaudi for reporting

> but the plot is generated with the last valid corr_coeff given.

I don't think I understand this. What is happening that's it's ignoring invalid input but not raising an error? Also can you please show exactly what the code says in the version you're looking at, per the [contribution guidelines](https://github.com/NeuromatchAcademy/course-content/blob/master/.github/contributing.md)? Thanks.

**Comment by FedeClaudi** [comment]
Sorry I hadn't seen the guidelines, let me try to give more details. 

In W1D5T1, Section 1, Exercise 1 students are asked to complete the function `def calculate_cov_matrix(var_1, var_2, corr_coef):` and then at the end of the exercise:

```
###################################################################
## TO DO for students: generate and plot bivariate Gaussian data with variances of 1
## and a correlation coefficients of: 0.8
## repeat while varying the correlation coefficient from -1 to 1
###################################################################
np.random.seed(2020)  # set random seed
variance_1 = 1
variance_2 = 1
corr_coef = 0

# Uncomment to test your code and plot
cov_matrix = calculate_cov_matrix(variance_1, variance_2, corr_coef)
X = get_data(cov_matrix)
plot_data(X)
```

It's my understanding, but correct me if I'm wrong, that `corr_coef` can only be in range `[-1, 1]`. However you can define `corr_coeff` to be any arbitrary value and `calculate_cov_matrix` will still give you a result.

I thought the correct behaviour would be for the function to throw an error if the value is outside the valid range, instead of giving an output that I'm not sure how it should be interpreted.

I hope this clarifies what I mean, but do let me know if you need more info.

**Comment by mwaskom** [comment]
Isn't `calculate_cov_matrix` a function that students need to complete?

Unless there's something in the tutorial itself that is going to pass a correlation coefficient outside of [-1, 1] into this function (is a widget doing this?), I don't think we need to worry about making them do rigorous input checking...

Sorry, it's early here and I didn't get much sleep, so I might be missing something.

**Comment by FedeClaudi** [comment]
No I think you're getting it right. 

There's nothing in the tutorial itself that uses a `corr_coeff` out of range, but the exercise encourages the students to play around with `corr_coeff` to see what the resulting plots look like. 

Although the exercise states to use `corr_coeff` in range`[-1, 1]`:
```
## repeat while varying the correlation coefficient from -1 to 1
```
some of my students decided to play with larger values and where confused by the function's output they got. Both them and myself would've expected to get an error or no results, instead you get values that at first glance appear legit. 

As you say, the students need to complete the function themselves, but they're not instructed to enforce that the `corr_coeff` is in the correct range. 
It would be simple to add to the function:
```
if corr_coeff < -1 or corr_coeff > 1:
    raise ValueError(f'The correlation coefficient is not defined outside the range [-1, 1]. {corr_coeff} was passed instead')
```
this way there's no risk of confusion if a student accidentally passes an out of range value. In fact, in that case they'd be reminded that `corr_coeff` is only defined in range `[-1, 1]`.

**Comment by mwaskom** [comment]
We can leave the issue open for discussion during post-course revisions. I would be inclined to say that this is a good example of a situation where the Peer Programming approach can help resolve the confusion and lead to a deeper understanding than if the student just encountered an exception.

In general, I don't think we can or should commit to doing the kind of input validation that you would do in production code. But thanks for reporting!
