### ISSUE TITLE
W2D1 Tutorial1: in exercise 2B, two inputs are flipped for plot_visual function

### ISSUE THREAD

**Issue by mingyus** [NeuromatchAcademy/course-content#387]
(original post was incorrect... see below)

**Comment by mwaskom** [comment]
@mingyus how are you accessing the notebooks? In the current colab version, the function looks like this:

```python

def plot_visual(mu_visuals, mu_posteriors, max_posteriors):
    """
    Plots the comparison of computing the mean of the posterior analytically and
    the max of the posterior empirically via multiplication.
    
    Args:
        mu_visuals (numpy array of floats): means of the visual likelihood
        mu_posteriors (numpy array of floats):  means of the posterior, calculated analytically
        max_posteriors (numpy array of floats): max of the posteriors, calculated via maxing the max_posteriors.
        posterior (numpy array of floats): normalized probabilities for the posterior evaluated at each `x`
        
    Returns:
        Nothing.
    """
    fig_w, fig_h = plt.rcParams.get('figure.figsize')
    fig, ax = plt.subplots(nrows=2, ncols=1, figsize=(fig_w, 2 * fig_h))

    ax[0].plot(mu_visuals, max_posteriors, '-g', label='mean')
    ax[0].set_xlabel('Visual stimulus position')
    ax[0].set_ylabel('Multiplied posterior mean')
    ax[0].set_title('Sample output')

    ax[1].plot(mu_visuals, mu_posteriors, '--', color='xkcd:gray', label='argmax')
    ax[1].set_xlabel('Visual stimulus position')
    ax[1].set_ylabel('Analytical posterior mean')
    fig.tight_layout()
    ax[1].set_title('Hurray for math!')
```

**Comment by mwaskom** [comment]
Please see the [contributing guidelines](https://github.com/NeuromatchAcademy/course-content/blob/master/.github/contributing.md) for more information on what helps make an issue clear/actionable.

**Comment by mingyus** [comment]
Thanks for pointing me to the guidelines! 

Sorry I got confused... Yes the `plot_visual` function in the helper function is correct! (I'll edit my original post...)

The problem is the usage of the function later in the notebook (Section 3: exercise 2B). In the function definition, the second argument `mu_posteriors` is the analytical mean, and the third argument `max_posteriors` is the empirically integrated mean. Whereas in exercise 2, last line in the code block, the two inputs are flipped: `plot_visual(mu_visuals, mu_computational, mu_analytical)`.

**Comment by mrkrause** [comment]
Nice catch--they are swapped, though the broader point is that they're both identical. 
I'll try to push out a patch that fixes this shortly. 

Thanks for the careful review!

**Comment by mingyus** [comment]
Great, thank you @mrkrause !

Yes yes they should be identical! I only noticed this error because I had a bug in my own code that produced two different plots lol.
