### ISSUE TITLE
W2D1T3: too much confusion...

### ISSUE THREAD

**Issue by kevin-w-li** [NeuromatchAcademy/course-content#392]
This might be too late and the fixes will make the notebook inconsistent with the videos, I leave some notes here that discuss the interpretation of the variables and changes to the confusing axes labels.  I provide a link to the modified notebook at the end of [this post](https://neurostars.org/t/bayesian-brain-models-discussions-w2d1/14854/38)

**Comment by mwaskom** [comment]
Konrad just made a bunch of fixes and we're pushing an emergency fix. I'm going to close.
