### ISSUE TITLE
plot_myarray bug in W2D1 tutorial 3

### ISSUE THREAD

**Issue by cjungerius** [NeuromatchAcademy/course-content#401]
In the latest version of this notebook (per google colab) `ax.imshow` is called without origin argument, causing all colormaps in the notebook to be plotted in what appears to be reverse order from what is intended:
```python   
colormap = ax.imshow(array, extent=[-10, 10, 8, -8])
```

adding an origin='lower' argument, to start plotting the array from the bottom row up, appears to fix all the colormaps. Note that the examples will need to be replaced manually;

```python
colormap = ax.imshow(array, extent=[-10, 10, 8, -8], origin='lower')
```

**Comment by mwaskom** [comment]
The heatmap orientation went through two rounds of last minute changes last night, but I believe the latest version is now correct (the orientation of an imshow heatmap is overdetermined, origin is not strictly necessary).

If you are looking at the latest version of the notebook and think it’s wrong, can you please upload an example image and an image that you think would be correct?

**Comment by mwaskom** [comment]
Also just pedantically, the color map is how you map from the numeric value in each cell of the heatmap to an rgb value. Here we are using “viridis” as the color map. It’s distinct from the heatmap, which is the overall plot. If the colormap were reversed, we’d see bright colors for low probability and dark colors for high probability. 

It’s not a big deal, but given the overall confusion about these plots I want to make sure we’re taking about the same thing.

**Comment by cjungerius** [comment]
Regardless of imshow's  intended use, the imshow() call is the culprit of the bug here.

Here's what the figure looks like now: (note *anti-correlated* ~x and x, where one would expect a *correlated* one):
![image](https://user-images.githubusercontent.com/37599089/87942403-d0804e80-ca9c-11ea-922a-2bc4292a0188.png)

And here's what I believe it should look like, and what changes when `origin = 'lower'` is added to the imshow call (~x and x are correlated, as one would expect from a brain representation and the underlying stimulus):
![image](https://user-images.githubusercontent.com/37599089/87942511-fad20c00-ca9c-11ea-8535-be2148bfd89a.png)

Worth noting that 'overdetermined' has little meaning here, as imshow still has to be told to start drawing the image from the top or the bottom.

In case there's some uncertainty that my idea of the correlation of x and ~x is correct: Inspecting the data visually will reveal that this is the intended relationship (and is actually preserved in the underlying data):
```python
print(hypothetical_stim[0],x[np.argmax(likelihood_array[0,:])])
print(hypothetical_stim[-1],x[np.argmax(likelihood_array[-1,:])])
```
which returns
```
-8.0 -8.000000000000007
8.0 7.999999999999936
```

Note that this doesn't correspond to the graph as it is now!

**Comment by cjungerius** [comment]
And yes, I'm looking at the latest version of the notebook (I've been constantly reloading the google colab version to check if the error was indeed me using an old version, but it's still plotting it the wrong way around!)

**Comment by mwaskom** [comment]
All good. For the record:

> Worth noting that 'overdetermined' has little meaning here, as imshow still has to be told to start drawing the image from the top or the bottom.

It’s also possible to invert the y axis and change where it’s “top” or “bottom” appears. So between extent, origin, and the axis orientation, it’s possible to get the plot correct in multiple ways (and wrong in more ways, apparently).

Personally I find imshow really confusing and always use pcolormesh when I have a matrix and x/y coordinate grids. 

Anyway I think we agree the problem is resolved, so I’ll close.
