### ISSUE TITLE
W2D1 typos

### ISSUE THREAD

**Issue by da5nsy** [NeuromatchAcademy/course-content#409]
### T1

current:
> nHowever

suggested:
> However

### T3
current:
> The brain then combine this brain encoded stimulus

suggested:
> The brain then combines this brain-encoded stimulus

The combine needs an 's'.
I would recommend connecting 'brain encoded' to 'brain-encoded' as good practice.

**Comment by mwaskom** [comment]
Thanks @da5nsy for your close eye! Would it be possible to compile all typos and related low-level problems for each day [into a single issue](https://github.com/NeuromatchAcademy/course-content/blob/master/.github/contributing.md#be-organized), to keep the issue feed manageable? Thank you!

**Comment by da5nsy** [comment]
Noted! :)

**Comment by da5nsy** [comment]
> 
> 
> Would it be possible to compile all typos and related low-level problems for each day [into a single issue](https://github.com/NeuromatchAcademy/course-content/blob/master/.github/contributing.md#be-organized), to keep the issue feed manageable? Thank you!

I have edited this issue to fold in https://github.com/NeuromatchAcademy/course-content/issues/408.
