### ISSUE TITLE
W1D5 Tutorial 3 -can't load the MNIST dataset (ConnectionRefusedError)

### ISSUE THREAD

**Issue by ShiriMakov** [NeuromatchAcademy/course-content#425]
W1D5 Tutorial 3 -refuses to load the MNIST dataset (ConnectionRefusedError).

Full traceback:

/usr/local/lib/python3.6/dist-packages/sklearn/datasets/_openml.py:55: RuntimeWarning: Invalid cache, redownloading file
  warn("Invalid cache, redownloading file", RuntimeWarning)
---------------------------------------------------------------------------
ConnectionRefusedError                    Traceback (most recent call last)
/usr/lib/python3.6/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
   1324                 h.request(req.get_method(), req.selector, req.data, headers,
-> 1325                           encode_chunked=req.has_header('Transfer-encoding'))
   1326             except OSError as err: # timeout error

40 frames
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

URLError                                  Traceback (most recent call last)
URLError: <urlopen error [Errno 111] Connection refused>

During handling of the above exception, another exception occurred:

ConnectionRefusedError                    Traceback (most recent call last)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

URLError                                  Traceback (most recent call last)
/usr/lib/python3.6/urllib/request.py in do_open(self, http_class, req, **http_conn_args)
   1325                           encode_chunked=req.has_header('Transfer-encoding'))
   1326             except OSError as err: # timeout error
-> 1327                 raise URLError(err)
   1328             r = h.getresponse()
   1329         except:

URLError: <urlopen error [Errno 111] Connection refused>

**Comment by mwaskom** [comment]
Thanks, it seems back up now. This is the one course dataset we don't host ourselves. (It's on openml.org). I'm not sure what caused the outage.

**Comment by mwaskom** [comment]
Seems to have been a transient outage on https://www.openml.org/
