### ISSUE TITLE
W2D4: Exercise 6 slide bar names too long

### ISSUE THREAD

**Issue by kevin-w-li** [NeuromatchAcademy/course-content#431]
![image](https://user-images.githubusercontent.com/21148565/88229064-0aea1700-cc68-11ea-867c-c6c93c9e176d.png)
Please either shorten them or make the sliders more towards the right.

**Comment by ssn2500** [comment]
I think you are using an old version. This is already addressed in the current version.

**Comment by mrkrause** [comment]
Yup, the current version looks like this:

<img width="1099" alt="image" src="https://user-images.githubusercontent.com/3977675/88231192-c3509480-cc41-11ea-84ee-df99feda323d.png">
