### ISSUE TITLE
W2D4 tutorial 1

### ISSUE THREAD

**Issue by ShiriMakov** [NeuromatchAcademy/course-content#438]
In Exercise 3.2, it could be easier if the lower graph depicted the belief the fish were on the right.

**Comment by mwaskom** [comment]
Can you say more about what you mean by "it could be easier"?

**Comment by ShiriMakov** [comment]
Sure! There are 3 consecutive plots. In the top one, fish being on the right is at 1 and on the left at (-1), so the fish on the right is 'up' with higher values.
In the bottom graph, we see the belief the fish were on the left, so the high values relate to being on the left side.
I think it will be easier to be consistent and have one side (right/ left) always as a high value, it will be more readable.
+ I think that in the micro-tutorial it is like this.

Thanks for everything you're doing, you're the best :)

**Comment by ssnio** [comment]
addressed in the W2D4_PreCronical (#536)
