### ISSUE TITLE
W2D4 -- TA feedback

### ISSUE THREAD

**Issue by ollimuh** [NeuromatchAcademy/course-content#449]
# W2D4 - Optimal Control
## Bugs:
- ~~T2 equations below video 4, the equation for observation / measurement is written in terms of x_t whereas it should be written in terms of s_t to match the video & other notation~~

## Clarifications / Inconsistencies:
- ~~The first video of tutorial 1 was cut too drastically. Here is a better explanation of the decision processes: https://youtu.be/3oIwUFpolVA~~

- ~~T1 Ex 3.2: The top plot shows the state, and ‘right’ is up. Bottom plot shows belief on left, and 1 is up. This is slightly confusing, and also opposite of what is shown in the next video.~~

- ~~In T1 exercise 4 the students are asked to complete the function policy_threshold(); what is needed is an actual if-else statement, but the commented part to modify is a single line. Given that so far the tutorials indicated if multiple lines were needed with multiple commented lines, the current form may be quite confusing for the students.~~

- ~~T1 Exercise 5: argument ‘measurement’ is not described in a docstring~~

- The figures in T1 and T2 are in xkcd style, and once the students try to solve the exercises and run the cell they will lose a reference for seeing immediately if they got it or not.

- ~~T2 Section 4.1: no explanation or mention of what proc_noise and meas_noise are before it appeared in the widget of section 4.1 (they didn’t appear in the texts until section 4.4, and even in 4.4 there wasn’t really any explanation on what they are, particularly the process noise. People had to figure it out based on the effects of them, which added confusion).~~

## Questions:

- T2 Section 3 (time varying goal): I'm not sure I understand the change to the cost function. I would assume that the action cost (eg fuel expenditure) would depend solely on the final action a_t. Why should it 'care' about a_t_bar?
It actually seems like the effect of rho here (as seen in the interactive demo) is the opposite compared to the earlier section.

**Comment by ssnio** [comment]
The two remaining points were ambiguous and believed to have been fixed in earlier pulls (version updates).
