### ISSUE TITLE
W2D5 - how long is the US?

### ISSUE THREAD

**Issue by ShiriMakov** [NeuromatchAcademy/course-content#454]
In section 3 it says: "In this environment, we'll return to delivering a single reward of ten units".
However, it seems that the reward lasted only 1 time point.
Could that be clarified?

**Comment by mrkrause** [comment]
I assume this is for Tutorial 1?

In all of the environments, the rewards were only present on a single timestep. However, in the previous exercise, the environment delivered one of several different-sized rewards (depending on the values you entered). 

Would something like this be better?

> "As in Section 1, this environment only dispenses one size of reward. However, it will be delivered intermittently..."

**Comment by mwaskom** [comment]
“Units” is the magnitude, not the duration.

**Comment by ShiriMakov** [comment]
Ho thanks :)
