### ISSUE TITLE
Reinforcement Learning T3: the implementation of "action" in SARSA is repeated

### ISSUE THREAD

**Issue by willwayaka** [NeuromatchAcademy/course-content#459]
In current implementation of SARSA algorithm, the `policy_action` in the function `sarsa` to update the value for the next state, is not necessarily the actual next action the agent is going to take, which is determined by `action` in the Helper Function `learn_environment`. Per discussion with @marcelomattar on slack, the correct implementation would have ensured that the policy in `learn_environment` is the same as the one used for the SARSA update in `sarsa`.

**Comment by spirosChv** [comment]
This refers to old RL tutorials. Now in [W3D4_ReinforcementLearning](https://github.com/NeuromatchAcademy/course-content/tree/main/tutorials/W3D4_ReinforcementLearning)

**Comment by spirosChv** [comment]
This day has been fully updated in 2021.
