### ISSUE TITLE
[W3D1T2] typo in my_bins

### ISSUE THREAD

**Issue by kevin-w-li** [NeuromatchAcademy/course-content#466]
In the solution to Ex. 2, the function uses a global variable `my_bins` instead of the local keyword argument `bins`. 
Actionable: change the blue-highlighted to `bins`.
![image](https://user-images.githubusercontent.com/21148565/88489737-19993c80-cf8e-11ea-95ff-2c4f9266d1a9.png)

**Comment by ebatty** [comment]
Fixed, thanks!
