### ISSUE TITLE
W3D2 Wrong formula.

### ISSUE THREAD

**Issue by NeoNeuron** [NeuromatchAcademy/course-content#478]
https://github.com/NeuromatchAcademy/course-content/blob/655a35a7b14b69937471ceaf98580f51a7385333/tutorials/W3D2_DynamicNetworks/solutions/W3D2_Tutorial1_Solution_ff61ccd4.py#L13

Here, we might miss brackets for the right hand side of the original equation. I put the corrected version below.
```
drdt = ( -r + F(w * r + I_ext, a, theta) ) / tau 
```
Since we choose our default `tau = 1.0`, it does not make any difference. Otherwise, we may get wrong results.

**Comment by spirosChv** [comment]
Thank you very much for this catch! Indeed the formula was wrong. We have updated the solution cell accordingly.
