### ISSUE TITLE
W3D3T2 add selected neuron index to compute_connectivity_from_single_neuron

### ISSUE THREAD

**Issue by Visdoom** [NeuromatchAcademy/course-content#481]
In the function `compute_connectivity_from_single_neuron` in line 58 it should say
`estimated_connectivity = compute_connectivity_from_single_neuron(X,selected_neuron)` 
instead of 
`estimated_connectivity = compute_connectivity_from_single_neuron(X,1)`, otherwise it will only show the estimated connectivity of neuron 1.

**Comment by ebatty** [comment]
Fixed, thanks!
