### ISSUE TITLE
W2D1 - Wrong link at the end of Tutorial 3

### ISSUE THREAD

**Issue by vincentvalton** [NeuromatchAcademy/course-content#483]
At the end of W2D1 Tutorial 3, the link to Bonus tutorial 4 needs to be updated (it currently points to the pre-waxing Tutorial 4, as opposed to the waxed tutorial 4).

**Comment by mwaskom** [comment]
Oh thanks for catching, ideally the tutorials won't cross-link to each other at all, because it's too easy for that to get out of sync.
