### ISSUE TITLE
W3D3T1 Section 3 summation should be over timesteps

### ISSUE THREAD

**Issue by marinafridman** [NeuromatchAcademy/course-content#490]
Hello,

I'm not sure, but I think for the equations to find the delta for each neuron on another neuron, the summation should be over timesteps. Currently there is an i under the summation sign, suggesting the summation is over neurons.

Thanks!

**Comment by aribenjamin** [comment]
Yes, I can confirm this is a typo. The summation should be over t and furthermore every other timestep. The equation in section 3.1

> $$
> \delta_{x^i\to x^j} \approx \frac1N \sum_i^N[x_{t+1}^j | x^i_t=1] -  \frac1N \sum_i^N[x_{t+1}^j | x^i_t=0]
> $$

Should be 

$$
\delta_{x^i\to x^j} \approx \frac1N \sum_{\substack{t=0 \\ t \text{ even}}}^N[x_{t+1}^j | x^i_t=1] -  \frac1N \sum_{\substack{t=0 \\ t \text{ even}}}^N[x_{t+1}^j | x^i_t=0]
$$
