### ISSUE TITLE
[W3D4T1] Typo in comment

### ISSUE THREAD

**Issue by kevin-w-li** [NeuromatchAcademy/course-content#493]
`NLLLoss` is not MSE. Change MSE to cross-entropy. Refer to text above that talks about `NLLLoss`.

![image](https://user-images.githubusercontent.com/21148565/88804706-35772b00-d1a6-11ea-93cd-295882517f10.png)

**Comment by spirosChv** [comment]
Has been fixed in the 2021 version of NMA-CN.
