### ISSUE TITLE
W3D5 T2: in Section 3.5, phi and theta should be swapped

### ISSUE THREAD

**Issue by zuxfoucault** [NeuromatchAcademy/course-content#503]
`phi` and `theta` in the equation should be swapped to match the figure.
![Screen Shot 2020-07-30 at 22 45 30](https://user-images.githubusercontent.com/3050531/88943371-f3d9a380-d2bd-11ea-9da1-dd9bc5aa0824.png)

**Comment by mwaskom** [comment]
I think that the code and videos are consistent with the equation, so the easiest fix is finding a different figure.

**Comment by spirosChv** [comment]
The figure has been changes in 2021 version of the course.
