### ISSUE TITLE
W3D5 T2: binder badge failed to render T2 notebook 

### ISSUE THREAD

**Issue by zuxfoucault** [NeuromatchAcademy/course-content#506]

**Comment by mwaskom** [comment]
We don’t provide binder badges. Do you mean  If so, this is a duplicate of #210. I don’t know that there’s anything we can do here, it may be a bug in nbviewer.

**Comment by zuxfoucault** [comment]
yes, nbviewer. Since it's duplicate, I'll close this issue here.
