### ISSUE TITLE
Reinforcement Learning -- TA feedback

### ISSUE THREAD

**Issue by ollimuh** [NeuromatchAcademy/course-content#507]
Clarifications / Inconsistencies:
(report when something needs clarification (+suggest a clarification))

Clarifications for T1:
The CS shows up at timestep 10
The US shows up at timestep 20 (coincidentally with a reward magnitude of 10)
is_delay is 1 for all timesteps after the CS (everything beyond 10). This means that everything before timestep 10 should have 0 value.
The goal of learning is that at the end of all trials, animals are supposed to know that the CS is *predictive* of the US (reward)
TD error == (the reality of the current state, according to the current reward and potential future value/rewards) - (the value of the current state that you expected, or previously thought would be reality)

~~T1: In interactive demo 2, it’s impossible to truly set alpha to zero (ie no learning), even though the number 0.00 is shown (this is slightly confusing)~~
T1: In interactive demo 2: What is so special about states 9 and 19? Is at a position of a cue & of a reward? Maybe it would be better to explain it in the plot?
~~T2 section 2: maybe it will be less confusing to write q(a,s) = q(a) = … and comment that this environment does not change its state? Otherwise it is hard to relate it to the intro video.~~
T2: maybe add alpha=0.7 to plot_parameter_performance? It is not clear which epsilon is better in section 4.

**Comment by spirosChv** [comment]
The day has been fully updated last year.
