### ISSUE TITLE
Biological Neuron Models - TA feedback

### ISSUE THREAD

**Issue by ollimuh** [NeuromatchAcademy/course-content#508]
## Bugs:
(report potential bugs / errors here (ideally along with a solution))

~~T1: Please call the CV ‘coefficient of variation’ (and not ‘variance’)~~

~~T3, Equation (6): t_sp and t_k somewhat unclear and probably the same (from subsequent formulation, but sum missing). u_E^+ and R_E^- in the third equation should be replaced by their dynamic versions (u_E and R_E), otherwise the first two equations are irrelevant for the dynamics of the synaptic conductances.~~

## Questions:
(report here when something is unclear and you don’t have a fix)

~~T2, section 3.2: I’m confused by the explanation of the last discussion question as the sentences are incomplete and also very vague (“For spike trains, if we do not have explicit control over mu and sigma. And these two variables will be tied to the firing rate of the inputs. So the results will be qualitatively similar.”).~~

T3, section 1: My pod was confused about both discussion questions at the end of this section, as well as the explanations/answers to them.

**Comment by ebatty** [comment]
Struck out parts fixed in #533

**Comment by spirosChv** [comment]
This refers to [W2D3_BiologicalNeuronModels](https://github.com/NeuromatchAcademy/course-content/tree/main/tutorials/W2D3_BiologicalNeuronModels).

**Comment by spirosChv** [comment]
The remaining points have been addressed.
