### ISSUE TITLE
DynamicNetworks - TA feedback

### ISSUE THREAD

**Issue by ollimuh** [NeuromatchAcademy/course-content#509]
## Bugs:
(report potential bugs / errors here (ideally along with a solution))

T1: It’s confusing that in video 1 the dynamics are described with a different formula than the texts right below it (the text has the extra wr term which isn’t discussed until the second video). It looks like either one of them needs to be fixed or there needs to be more explanations on this.

~~T1 section 1.3: In earlier sections a and theta were parameters to the function F, but here they somehow become parameters to Iext . Iext isn’t even a function in earlier or later sections.~~

~~T1 last discussion questions (“Think!”): wEE appeared completely out of context here. It wasn’t introduced until the first video of T2.~~

**Comment by ebatty** [comment]
Struck through parts fixed by #533

**Comment by spirosChv** [comment]
This refers to [W2D4_DynamicNetworks](https://github.com/NeuromatchAcademy/course-content/tree/main/tutorials/W2D4_DynamicNetworks).

**Comment by spirosChv** [comment]
The issue has been addressed, and the formula indicated in the slide is the same with the one given in text with the external current.
