### ISSUE TITLE
W3D3 -- TA feedback

### ISSUE THREAD

**Issue by ollimuh** [NeuromatchAcademy/course-content#510]
## Minor issues / Typos:
(collecting typos and minor issue here for creating a summary issue on Github)
[W3D3T2] exercise 1: my pod set the selected_neuron = 0 and got confused that estimated connectivity did not look like true connectivity. We figured out that the colorbar scale was not the same for the two plots. Suggestion: Please fix the scales of graphs to same min-max values or display the min and max scale values in all figures.

**Comment by ebatty** [comment]
This was an issue we thought carefully about - the scales do not match (we're getting a proportional estimated connectivity matrix as explained in the T1 appendix). so we can't fix the scales of the graphs to the same min-max values or you can't see the proportional similarity. We did not display the min/max values so as not to confuse people but maybe this was the wrong choice.

**Comment by mwaskom** [comment]
I think that doing the comparison this way is going to cause confusion somewhere, but having different min/max values on the plots is not obviously less confusing than the current approach. Using unlabeled scales can communicate (perhaps not completely effectively) that the scales should be thought of as relative, not absolute. So I support keeping the existing figures.
