### ISSUE TITLE
Post-course 2020 minor issue fixing

### ISSUE THREAD

**Issue by ebatty** [NeuromatchAcademy/course-content#524]
The goal here is to fix many of the minor issues (typos/code problems/confusing phrasings/etc) that were raised during the course. Please mention issues in PR and close them if fixed. If you can't do everything in a given issue, edit the issue to strikethrough the parts you have fixed.

This should be done after the notebooks have had their outputs stripped. Also when possible (when not shown in video), fix colors to be colorblind-friendly.

Here is a To-Do list to track which days have been updated and who is working on what. Assign yourself by editing the issue; check the box when you've finished the work:

- [x] W0D1 (JAL)
- [x] W0D2 (JAL)
- [x] W1D1 (EB)
- [x] W1D2 (EB)
- [x] W1D3 (EB)
- [x] W1D4 (EB)
- [x] W1D5 (EB)
- [x] W2D1 (JAL)
- [x] W2D2 (JAL)
- [x] W2D3 (JAL)
- [x] W2D4 
- [x] W2D5 (JAL)
- [x] W3D1 (EB)
- [x] W3D2 (EB)
- [x] W3D3 (EB)
- [x] W3D4 (EB)
- [x] W3D5 (EB)

**Comment by JesseLivezey** [comment]
Should we also change any RGB color choices to the default cycle in this pass? I think there were only a few figures where this would change.

**Comment by mwaskom** [comment]
I think that's generally a good idea for both aesthetic and accessibility reasons, but watch out for cases where the plot will look different than the video (@ebatty  things this is a big problem, I'm a bit less concerned by it) or where the text refers to colors by name (which can and should be changed, but are a problem if missed).

If there is an RGB plot in the video and we want to change the colorscheme, we can perhaps use the `C0`, `C1`, `C2` labels to map red -> orange, green -> green, blue-> blue, so the plot ends up looking basically like the video.

**Comment by ebatty** [comment]
I don't think this is a big problem if we can do small shifts like that! I just saw a few examples where the colors in the tutorial were opposite those in the video etc, which would be really confusing

**Comment by mwaskom** [comment]
OK good — I agree: trying to use the colors from the default (semi-colorblind friendly) cycle is much better than "r", "g", "b", but we should strive to align the hues roughly with what appears in the video.

**Comment by JesseLivezey** [comment]
These have all been merged!
