### ISSUE TITLE
Little issue on W0D1 (ex7)

### ISSUE THREAD

**Issue by alandrade1** [NeuromatchAcademy/course-content#538]
The exercise 7 has a broken link (the solution link does not work).

https://github.com/NeuromatchAcademy/course-content/tree/master//tutorials/W0D1_PythonWorkshop1/solutions/W0D1_Tutorial1_Solution_c3654fed.py

**Comment by JesseLivezey** [comment]
The W0 tutorials were recently updated, and the solution links change when that happens. If you re-open the notebook from github (refresh the page if you currently have it open), you should have working solution links.

For instance, the Ex7 link now points to:
https://github.com/NeuromatchAcademy/course-content/blob/master/tutorials/W0D1_PythonWorkshop1/solutions/W0D1_Tutorial1_Solution_41355f96.py
