### ISSUE TITLE
Issue on page /tutorials/W0D3_LinearAlgebra/student/W0D3_Tutorial2.html

### ISSUE THREAD

**Issue by tanyarubi** [NeuromatchAcademy/course-content#631]
I might be missing something, but in the second code snippet, I don't get where G and L are supposed to come from. I don't see that they'd been defined anywhere.

**Comment by da5nsy** [comment]
Hi @tanyarubi - I think there might be some crossed wires somewhere - I don't see any G and L in W0D3T2. Are you able to clarify?

**Comment by spirosChv** [comment]
The precourse tutorials have been moved to https://github.com/NeuromatchAcademy/precourse. I cannot see G and L on W0D3T2.
