### ISSUE TITLE
Formatting tiny errors in W0D3 tutorial1

### ISSUE THREAD

**Issue by ufangYang** [NeuromatchAcademy/course-content#654]
There is an extra comma and typo in the vector b in the 2.1: Determining dependence part:

typo issue: 
"Determining dependence": there is a missing 'n' for  "Determining"

comma issue

The comma after 3 in  the vector b should be removed:

```
# original 
 \end{bmatrix},  \mathbf{b} = \begin{bmatrix}
    1 \\ 0 \\ 3, 
```

```
# suggestion
 \end{bmatrix},  \mathbf{b} = \begin{bmatrix}
    1 \\ 0 \\ 3
```

Let me know if it will be easier if I modify it on the colab files. Thanks!

**Comment by da5nsy** [comment]
Another formatting error around the same point so I'll add on here:

The closing curly brackets on the following two questions appear to be accidentally outside of the math formatting.

> 4. What is the span of a set just consisting of vector {a} (in general terms)?
> 5. What is the span of the set of vectors {a,b} (in general terms)?

**Comment by spirosChv** [comment]
Fixed on the new [repo](https://github.com/NeuromatchAcademy/precourse) of pre-course material. Thanks! If the issue persists, please report an issue on the precourse repo. Thank you
