### ISSUE TITLE
Questions on Colab->Github workflow in reviewing-tutorials.md

### ISSUE THREAD

**Issue by msarvestani** [NeuromatchAcademy/course-content#68]
Re #6. If the QC workflow fails, revise the notebook on Colab then repeat Step 3.

What indicates that the QC has failed?

Re #7. Once the final pieces (e.g. video links) are in place, repeat Step 2 and Step 3, then remove the "draft" status from the PR on github and @ the reviewers for the merge.

How is the merge allowed without reviewers?

**Comment by mwaskom** [comment]
> What indicates that the QC has failed

Near the bottom of the PR page, there's a dialogue with the Checks and Merge button. A failed QC run will say "All checks have failed" and if you click "Details" you will go to the Actions interface where (with enough poking around) you can see more information about the specific problem.

<img width="697" alt="image" src="https://user-images.githubusercontent.com/315810/85150718-e3df9600-b220-11ea-9c37-c8958abe5801.png">

You can see a live version here: https://github.com/mwaskom/nbci/pull/17

> How is the merge allowed without reviewers?

It's not, but I don't know whether reviewers get a notification when a "Draft" PR they're assigned is marked "Ready for review". So it's good practice to @ them in a comment, they way they get a notification and know to attend to the PR.

**Comment by msarvestani** [comment]
Thanks.
