### ISSUE TITLE
Bug / Typo in W0D5_Tutorial2_Solution_4e7f8943.py

### ISSUE THREAD

**Issue by lanluo9** [NeuromatchAcademy/course-content#681]
Line 60: `visual = my_gaussian(x, mu_visual, mu_visual)` should be `visual = my_gaussian(x, mu_visual, sigma_visual)`

At the moment the solution plot is wrong because of this.

**Comment by spirosChv** [comment]
Good catch! Corrected on the new [repo](https://github.com/NeuromatchAcademy/precourse) of pre-course material. Thanks!
