### ISSUE TITLE
W0D5 , tutorial1 , Interactive Demo 2.2 "Click for solution" does not working

### ISSUE THREAD

**Issue by m-abdollahi** [NeuromatchAcademy/course-content#685]
Hi!
"Click for solution" in the Interactive Demo 2.2 from W0D5_tutorial 1 Does not working, and also the solution file does not exist in github repo.
Thanks.

**Comment by spirosChv** [comment]
Has been fixed with https://github.com/NeuromatchAcademy/course-content/pull/676
