### ISSUE TITLE
Missing bracket in derivative of rate (W0D4_Calculus/W0D4_Tutorial1)

### ISSUE THREAD

**Issue by alphydan** [NeuromatchAcademy/course-content#694]
in [tutorials/W0D4_Calculus/W0D4_Tutorial1.ipynb](https://github.com/NeuromatchAcademy/course-content/blob/master/tutorials/W0D4_Calculus/W0D4_Tutorial1.ipynb)  the following formula is missing a bracket:

`($\\frac{d(r(I)}{dI}$)`  

Should instead read

`($\\frac{d(r(I))}{dI}$)`

The line is here:
>     "The slope of a neurons input-output transfer function ($\\frac{d(r(I)}{dI}$) is called the **gain** of the neuron, as it tells how the neuron output will change if the input is changed. In other words, the slope of the transfer function tells us in which range of inputs the neuron output is most sensitive to changes in its input. \n"

**Comment by spirosChv** [comment]
Fixed on the new [repo](https://github.com/NeuromatchAcademy/precourse) of pre-course material. Thanks!
