### ISSUE TITLE
W1D4, T2, CV value in tutorial not obvious

### ISSUE THREAD

**Issue by ematiss** [NeuromatchAcademy/course-content#756]
# Exercise 3.4

**course-content/tutorials/W1D4_GeneralizedLinearModels/W1D4_Tutorial2.ipynb**
The choice of cv is not obvious here and can lead to similar but different graphs when compared to the xkcd solution. Mentioning `k=8` might help in the comments.

```
    # Get the accuracy for each test split using cross-validation
    accs = cross_val_score(model, X, y, cv=8)
```

**Comment by spirosChv** [comment]
Thanks. With https://github.com/NeuromatchAcademy/course-content/pull/830 we have added in the instructions the value of `k`.
