### ISSUE TITLE
Issue on function my_illus_LIFSYN(pars, v_fmp, v)

### ISSUE THREAD

**Issue by eduardoconto** [NeuromatchAcademy/course-content#773]
For coding exercise 1.2, changing the threshold doesn't seem to have any effect. 
I think there is a bug in def my_illus_LIFSYN(pars, v_fmp, v)

```
Line
  plt.axhline(-55, 0, 1, color='k', lw=2., ls='--',
              label='Spike Threshold', zorder=1
 Should be 
 plt.axhline(pars['V_th'], 0, 1, color='k', lw=2., ls='--',
              label='Spike Threshold', zorder=1)
```

**Comment by spirosChv** [comment]
Good catch, thanks. https://github.com/NeuromatchAcademy/course-content/pull/830 fixed the hardcoded value.
