### ISSUE TITLE
Typo in notation in W3D1_Tutorial1

### ISSUE THREAD

**Issue by formozov** [NeuromatchAcademy/course-content#796]
P(m = fish) = P(m = fish, s = left) + P(m = fish, s = right)
                = P(m = fish, s = left)P(s = left) + P(m = fish, s = right)P(s = right)

It should be 

P(m = fish) = P(m = fish, s = left) + P(m = fish, s = right)
                = P(m = fish | s = left)P(s = left) + P(m = fish | s = right)P(s = right)

The same for "2".

**Comment by spirosChv** [comment]
Thnaks, https://github.com/NeuromatchAcademy/course-content/pull/830 corrected the typos.
