### ISSUE TITLE
 conditional sigmas in W3D1_Tutorial2

### ISSUE THREAD

**Issue by ferchaure** [NeuromatchAcademy/course-content#800]
Hi, on tutorials/W3D1_BayesianDecisions/W3D1_Tutorial2.ipynb
the lines 304 and 305, should be: 

"    sigma_x_y = np.sqrt(sigma1**2 * (1-corr**2))\n",
"    sigma_y_x = np.sqrt(sigma2**2 * (1-corr**2))\n",

**Comment by spirosChv** [comment]
Thank you for reporting. https://github.com/NeuromatchAcademy/course-content/pull/809 fixed this issue.
