### ISSUE TITLE
Colab links are broken / don't point to master

### ISSUE THREAD

**Issue by patrickmineault** [NeuromatchAcademy/course-content#81]
When you pull a colab from somewhere else, the link that colab auto-adds at the top of the ipython notebook links to the specific branch that the colab was saved to, not to master. Example:

https://github.com/NeuromatchAcademy/course-content/pull/80/files

One points to the day06 branch, the other to Madineh's GH.

**Comment by mwaskom** [comment]
Well that's annoying.
