### ISSUE TITLE
Cannot build book locally

### ISSUE THREAD

**Issue by jreus** [NeuromatchAcademy/course-content#820]
Hello, in the README file for building the book locally, there is a python script we are asked to run:
```
python ci/generate_book.py
```

However there does not seem to be a `ci` directory, or a `generate_book.py` script in the repository!

**Comment by spirosChv** [comment]
We've split the CI tools off into a [separate repository](https://github.com/neuromatchAcademy/nmaci) so that they can be shared between the CN and DL courses. 

`ci` mentioned above, is the same as `nmaci`.

Try these commands:

```
git clone https://github.com/NeuromatchAcademy/nmaci.git
python nmaci/generate_book.py
```
