### ISSUE TITLE
jupyter book formatting issue on W0D3T1

### ISSUE THREAD

**Issue by da5nsy** [NeuromatchAcademy/course-content#821]
In the Jupyter Book rendering two of the images don't render correctly:

<img width="953" alt="Screenshot_20210803_111740" src="https://user-images.githubusercontent.com/3739866/128041412-3dbbf851-77f2-4765-b92d-f76aeb964f2d.png">

**Comment by spirosChv** [comment]
Corrected on the new [repo](https://github.com/NeuromatchAcademy/precourse) of pre-course material. Thanks!
