### ISSUE TITLE
FingerFlex dataset colab-notebook

### ISSUE THREAD

**Issue by EitanHemed** [NeuromatchAcademy/course-content#822]
### Problem description
EDIT - for clarification, the FingerFlex notebook was accessed from [here](https://compneuro.neuromatch.io/projects/ECoG/README.html).

In the notebook **course-content/projects/ECoG/load_ECoG_fingerflex.ipynb**, running the cell titled 'Data Loading' results in an error:

```#@title Data loading
import numpy as np

alldat = np.load(fname, allow_pickle=True)['dat']

# Select just one of the recordings here. This is subject 1, block 1.
dat = alldat[0]

print(dat.keys())
#  AttributeError: 'numpy.ndarray' object has no attribute 'keys'
```

The array `dat` is an ndarray, rather than a dictionary (or a NumPy records array). 

### Proposed bug-fix
In accordance with the comment in the code - a possible solution would be the to change the line `dat = alldat[0]` into `dat = alldat[0][0]` so `dat` would be assigned the dictionary that stores the data from the first block of the first subject.

Thanks!

**Comment by spirosChv** [comment]
Good catch, thanks. https://github.com/NeuromatchAcademy/course-content/pull/830 fixed it.
