### ISSUE TITLE
Issue on page /tutorials/W0D1_PythonWorkshop1/student/W0D1_Tutorial1.html

### ISSUE THREAD

**Issue by jeremy-fgn** [NeuromatchAcademy/course-content#852]
**W0D1_Tutorial1**
**Coding Exercise 4: Simulating membrane potential**
Issue : SAMPLE OUTPUT is misaligned by 1 line.

Current SAMPLE OUTPUT :
0.000 -6.0000e-02
0.001 -5.8750e-02
0.002 -5.6828e-02
0.003 -5.4548e-02
0.004 -5.2381e-02
0.005 -5.0778e-02
0.006 -4.9989e-02
0.007 -4.9974e-02
0.008 -5.0414e-02
0.009 -5.0832e-02

Corrected SAMPLE OUTPUT :
0.000 -5.8750e-02
0.001 -5.6828e-02
0.002 -5.4548e-02
0.003 -5.2381e-02
0.004 -5.0778e-02
0.005 -4.9989e-02
0.006 -4.9974e-02
0.007 -5.0414e-02
0.008 -5.0832e-02
0.009 -5.0775e-02

**Comment by spirosChv** [comment]
Can you please report this issue on [precourse](https://github.com/NeuromatchAcademy/precourse/issues) repo?
