### ISSUE TITLE
Instruction notebooks for IBL dataset: fix URL

### ISSUE THREAD

**Issue by anne-urai** [NeuromatchAcademy/course-content#882]
On the [IBL behavioral data projects page](https://compneuro.neuromatch.io/projects/behavior/README.html), the 3 example notebooks in Colab point to `main` as the branch, whereas the [source repo](https://github.com/int-brain-lab/nma-ibl) still uses `master`. Updating this would fix the Colab links and Nbviewer.

**Comment by spirosChv** [comment]
Thank you for reporting this. The changes have been pushed on github and they will be visible on jupyter-book in 30-40 mins.
