### ISSUE TITLE
Broken formula in `W3D5_Tutorial1.ipynb`

### ISSUE THREAD

**Issue by kir0ul** [NeuromatchAcademy/course-content#948]
Hi, there's some broken LaTeX code for the formula in [`W3D5_Tutorial1.ipynb`](https://github.com/NeuromatchAcademy/course-content/blob/main/tutorials/W3D5_NetworkCausality/W3D5_Tutorial1.ipynb) in Section 1 under video 1:
```latex
\begin{equation}
\delta_{A\to B} = \mathbb{E}[B | A=1] -  \mathbb{E}[B | A=0] 
\begin{equation}
```
which should be:
```latex
\begin{equation}
\delta_{A\to B} = \mathbb{E}[B | A=1] -  \mathbb{E}[B | A=0] 
\end{equation}
```

**Comment by spirosChv** [comment]
Thank you, @kir0ul for reporting it, good catch! We have fixed it and pushed the changes on Github.
