### ISSUE TITLE
Issue on page /tutorials/W2D3_BiologicalNeuronModels/student/W2D3_Tutorial2.html

### ISSUE THREAD

**Issue by aoot** [NeuromatchAcademy/course-content#956]
The definition of the function `corr_coef_pairs()` should replace the `n_trials` variable with `trials`, as `trials` is an argument provided to the function, whereas `n_trails` is a global variable declared after the function definition.

![image](https://user-images.githubusercontent.com/9303869/201233837-188a9862-7229-4b41-a7f7-0e7e08c7eb33.png)

**Comment by spirosChv** [comment]
Good catch! https://github.com/NeuromatchAcademy/course-content/pull/958 fixed this.
